### ISSUE TITLE
SSL Certs Missing

### ISSUE THREAD

**Issue by vitoscalleta** [gary-archer/oauth.websample.azure#7]
Hi .

As per your guide in the [link](https://authguidance.com/2017/11/30/azure-active-directory-setup/) there should be a list of SSL Certificates in the folder ./.certs/localhost/.

But in the latest repository there are not certs and I am getting the following error while trying to run the application.

![image](https://user-images.githubusercontent.com/29479953/134177372-3c1c8129-5ea9-41d0-aa71-620d4c36ea63.png)

Were the certs removed from this repo and moved to some other repo ?

**Comment by gary-archer** [comment]
Apologies but I missed this message - so my answer is probably a bit late for you. I did a bit of housekeeping today and hopefully made the repo a little easier to run by updating to a `build script` and `deployment script` model. I hope the README is a little clearer, though blog posts need updating, and I'll do that in the next couple of weeks. 

Basically I have a bunch of repos that use SSL and I keep the certs [here](https://github.com/gary-archer/oauth.developmentcertificates) so that I can maintain them in one place. But there was a bug in my repo's code.

**Comment by vitoscalleta** [comment]
Thanks. Better late than never. 
I am checking if I can end do end on that guide again. Thanks

**Comment by gary-archer** [comment]
Fixed
